version = 0.1

[default.deploy.parameters]
stack_name = "SandhyaPortfolioBackend"
resolve_s3 = true
s3_prefix = "SandhyaPortfolioBackend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "RecaptchaSecretName=\"PortfolioRecaptchaSecret\" PrivateFunctionName=\"PortfolioSendEmailFunction\""
image_repositories = []
